Repository civitai/civitai, pull requests merged in 2024-11, with the labels that each got.

#1470 Update BountyUpsertForm.tsx
  src/components/Bounty/BountyUpsertForm.tsx
Labels: enhancement

#1472 Update tos.md
  src/static-content/tos.md
Labels: enhancement

#1478 Trigger words for Training
  src/components/Training/Form/TrainingBasicInfo.tsx
  src/components/Training/Form/TrainingImages.tsx
  src/components/Training/Form/TrainingParams.tsx
  src/components/Training/Form/TrainingSubmit.tsx
  src/components/Training/Form/TrainingSubmitAdvancedSettings.tsx
  src/server/controllers/model.controller.ts
  src/server/controllers/training.controller.ts
  src/store/training.store.ts
  src/utils/notifications.tsx
Labels: deploy-dev

#1479 Update blocklist-nsfw.json
  src/utils/metadata/lists/blocklist-nsfw.json
Labels: enhancement

#1480 Vault Copy Updates
  src/components/Stripe/MembershipChangePrevention.tsx
  src/components/Subscriptions/CancelMembershipMenuItem.tsx
Labels: enhancement

#1483 User Account Refresh Session Buttton
  src/components/Account/RefreshSessionCard.tsx
  src/pages/user/account.tsx
Labels: enhancement

#1487 fix/link-copy-update Update copy on Civitai Link page
  src/pages/product/link.tsx
Labels: enhancement

#1506 add search box for notifications
  src/components/Chat/ChatList.tsx
  src/components/Chat/ExistingChat.tsx
  src/components/Notifications/NotificationList.tsx
  src/components/Notifications/NotificationTabs.tsx
  src/components/Notifications/NotificationsComposed.tsx
Labels: deploy-dev

#1502 Feature/snigel
  src/components/Ads/AdUnit.tsx
  src/components/Ads/AdUnitFactory.tsx
  src/components/Ads/AdUnitRenderable.tsx
  src/components/Ads/AdsProvider.tsx
  src/components/Ads/ads.utils.ts
  src/components/Ads/types.ts
  src/components/BrowsingLevel/BrowsingLevelProvider.tsx
  src/components/Chat/ChatProvider.tsx
  src/components/HomeBlocks/CollectionHomeBlock.tsx
  src/components/Image/DetailV2/ImageDetail2.tsx
  src/components/Image/DetailV2/ImageDetailCarousel.tsx
  src/components/MasonryColumns/MasonryColumns.tsx
  src/components/MasonryColumns/MasonryGrid.tsx
  src/components/MasonryColumns/masonry.utils.ts
  src/components/Model/ModelVersions/ModelVersionDetails.tsx
  src/components/Post/Detail/PostDetail.tsx
  src/components/TrackView/TrackPageView.tsx
  src/components/WatchAdButton/WatchAdButton.tsx
  src/libs/auth.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/home.tsx
  src/server/services/feature-flags.service.ts
  src/static-content/privacy.md
  src/styles/globals.css
Labels: deploy-stage

#1514 Update ProfileCard.tsx
  src/components/Account/ProfileCard.tsx
Labels: enhancement
