Repository civitai/civitai, pull requests merged in 2025-04, with the labels that each got.

#1672 feature/video-training
  README.md
  containers/clickhouse/docker-init/init.sh
  prisma/migrations/20250326094141_covered_checkpoint/migration.sql
  scripts/local-dev/gen_seed.ts
  scripts/local-dev/run_migrations.ts
  src/components/Image/Filters/MediaFiltersDropdown.tsx
  src/components/ImageGeneration/GenerationForm/resource-select.types.ts
  src/components/Resource/Forms/TrainingSelectFile.tsx
  src/components/Training/Form/ImageSelectFilters.tsx
  src/components/Training/Form/ImageSelectModal.tsx
  src/components/Training/Form/TrainingAutoLabelModal.tsx
  src/components/Training/Form/TrainingBasicInfo.tsx
  src/components/Training/Form/TrainingCommon.ts
  src/components/Training/Form/TrainingEditTagsModal.tsx
  src/components/Training/Form/TrainingImages.tsx
  src/components/Training/Form/TrainingImagesCaptionViewer.tsx
  src/components/Training/Form/TrainingImagesTagViewer.tsx
  src/components/Training/Form/TrainingParams.tsx
  src/components/Training/Form/TrainingSubmit.tsx
  src/components/Training/Form/TrainingSubmitAdvancedSettings.tsx
  src/components/Training/Form/TrainingSubmitModelSelect.tsx
  src/components/Training/Wizard/TrainWizard.tsx
  src/server/common/constants.ts
  src/server/common/enums.ts
  src/server/http/orchestrator/orchestrator.types.ts
  src/server/jobs/handle-auctions.ts
  src/server/schema/model-version.schema.ts
  src/server/services/feature-flags.service.ts
  src/server/services/model-file.service.ts
  src/server/services/orchestrator/training/training.orch.ts
  src/server/services/training.service.ts
  src/store/training.store.ts
  src/utils/training.ts
  tests/example.spec.ts
Labels: deploy-dev

#1677 Feature/clavata
  prisma/migrations/20250414192734_tag_type/migration.sql
  prisma/migrations/20250416221729_shadow_tags_on_image/migration.sql
  prisma/schema.prisma
  src/env/schema.ts
  src/pages/api/webhooks/image-scan-result.ts
  src/server/common/enums.ts
  src/server/services/image.service.ts
  src/shared/utils/prisma/enums.ts
  src/shared/utils/prisma/models.ts
Labels: deploy-stage

#1682 feature/wan-training
  src/components/Training/Form/TrainingParams.tsx
  src/components/Training/Form/TrainingSubmit.tsx
  src/server/jobs/handle-auctions.ts
  src/server/schema/model-version.schema.ts
  src/utils/training.ts
Labels: deploy-dev

#1695 Update Character LoRA Image
  src/components/Training/Form/TrainingBasicInfo.tsx
Labels: enhancement

#1698 POI update
  src/utils/metadata/lists/words-poi.json
Labels: enhancement

#1696 Add simple A-Z sorting on My Collections
  src/components/Collections/CollectionsLayout.tsx
  src/components/Collections/MyCollections.tsx
Labels: enhancement
