Repository civitai/civitai, pull requests merged in 2025-01, with the labels that each got.

#1560 Update AppFooter.tsx
  src/components/AppLayout/AppFooter.tsx
Labels: enhancement

#1561 Improve performance of EdgeMedia component (videos)
  src/client-utils/cf-images-utils.ts
  src/components/EdgeMedia/EdgeImage.module.scss
  src/components/EdgeMedia/EdgeImage.tsx
  src/components/EdgeMedia/EdgeMedia.tsx
  src/components/EdgeMedia/EdgeVideo.tsx
  src/components/EdgeMedia/EdgeVideoBase.tsx
  src/components/EdgeMedia/EdgeVideoWithControls.tsx
  src/components/Post/EditV2/PostImageCards/AddedImage.tsx
  src/components/ScrollArea/ScrollAreaContext.ts
  src/components/UserAvatar/UserAvatarSimple.tsx
Labels: deploy-stage

#1576 Rule Addition - Daily Challenges
  src/server/games/daily-challenge/generative-content.ts
Labels: enhancement

#1575 Update Data Retention Policy
  src/static-content/training/data-policy.md
Labels: enhancement

#1579 Fix/generation copy update
  src/components/ImageGeneration/GeneratedImageActions.tsx
  src/components/ImageGeneration/Queue.tsx
Labels: enhancement

#1581 Update POI rules on Safety Center
  src/static-content/rules/real-people.md
Labels: enhancement

#1565 [CU-868bm9mq9] Allows scheduled publishing without file uploads
  src/components/Resource/Forms/ModelVersionUpsertForm.tsx
  src/components/Resource/Forms/PostUpsertForm2.tsx
  src/server/jobs/process-scheduled-publishing.ts
Labels: deploy-dev

#1595 Feature/generation only models
  prisma/migrations/20250122210402_model_usage_control/migration.sql
  prisma/schema.prisma
  src/components/Model/ModelVersions/ModelVersionDetails.tsx
  src/components/Model/ModelVersions/model-version.utils.ts
  src/components/Resource/Forms/ModelVersionUpsertForm.tsx
  src/pages/api/download/models/[modelVersionId].ts
  src/pages/api/download/vault/[vaultItemId].ts
  src/pages/api/v1/model-versions/mini/[id].ts
  src/server/controllers/model-version.controller.ts
  src/server/controllers/model.controller.ts
  src/server/schema/model-version.schema.ts
  src/server/selectors/model.selector.ts
  src/server/selectors/modelVersion.selector.ts
  src/server/services/feature-flags.service.ts
  src/server/services/file.service.ts
  src/server/services/vault.service.ts
  src/shared/utils/prisma/enums.ts
  src/shared/utils/prisma/models.ts
  src/utils/string-helpers.ts
Labels: deploy-stage

#1600 whatIf request error message includes trial generation errors,
  src/components/ImageGeneration/GenerationForm/GenerationForm2.tsx
  src/components/ImageGeneration/GenerationForm/ResourceSelectCard.tsx
  src/components/ImageGeneration/GenerationForm/TextToImageWhatIfProvider.tsx
  src/components/ImageGeneration/utils/generationRequestHooks.ts
  src/components/Model/ModelVersions/ModelVersionEarlyAccessPurchase.tsx
  src/pages/api/v1/permissions/check.ts
  src/server/routers/orchestrator.router.ts
  src/server/services/orchestrator/workflows.ts
  src/store/model-version.store.ts
Labels: deploy-stage

#1602 Update DeleteCard.tsx
  src/components/Account/DeleteCard.tsx
Labels: enhancement
