Repository civitai/civitai, pull requests merged in 2025-02, with the labels that each got.

#1604 optimize fetching comment thread details
  prisma/migrations/20250131232938_comment_v2_pinned_at/migration.sql
  prisma/schema.prisma
  src/components/CommentsV2/Comment/Comment.tsx
  src/components/CommentsV2/Comment/CommentForm.tsx
  src/components/CommentsV2/Comment/CommentProvider.tsx
  src/components/CommentsV2/Comment/CommentReactions.tsx
  src/components/CommentsV2/Comment/DeleteComment.tsx
  src/components/CommentsV2/CommentsProvider.tsx
  src/components/CommentsV2/commentv2.utils.ts
  src/components/Model/Discussion/ModelDiscussionsCard.tsx
  src/components/Model/Discussion/ModelDiscussionsInfinite.tsx
  src/pages/api/admin/test.ts
  src/server/common/enums.ts
  src/server/controllers/commentv2.controller.ts
  src/server/routers/commentv2.router.ts
  src/server/schema/commentv2.schema.ts
  src/server/selectors/commentv2.selector.ts
  src/server/services/commentsv2.service.ts
  src/shared/utils/prisma/models.ts
Labels: deploy-dev

#1606 Upgrades prisma to v6 and improve query to image appeals
  package-lock.json
  package.json
  prisma/migrations/20250131152943_many_to_many_table_relation/migration.sql
  prisma/migrations/migration_lock.toml
  src/server/selectors/commentv2.selector.ts
  src/server/selectors/model.selector.ts
  src/server/selectors/modelHash.selector.ts
  src/server/selectors/reaction.selector.ts
  src/server/selectors/resourceReview.selector.ts
  src/server/selectors/tag.selector.ts
  src/server/services/image.service.ts
Labels: deploy-dev

#1608 clean up signal worker, fewer message types
  src/components/Signals/SignalsProvider.tsx
  src/server/routers/signals.router.ts
  src/server/services/feature-flags.service.ts
  src/utils/signals/index.ts
  src/utils/signals/types.ts
  src/utils/signals/useSignalsWorker.ts
  src/utils/signals/worker.ts
  src/utils/signals/worker.v1.2.ts
  tailwind.config.js
  tsconfig.json
Labels: deploy-stage

#1611 Feature/priority pricing 2
  package-lock.json
  package.json
  src/components/Buzz/BuzzTransactionButton.tsx
  src/components/Currency/CurrencyBadge.tsx
  src/components/Filters/AdaptiveFiltersDropdown.tsx
  src/components/Generation/Input/RequestPriority.tsx
  src/components/Image/DetailV2/ImageProcess.tsx
  src/components/ImageGeneration/GenerationForm/GenerationCostPopover.tsx
  src/components/ImageGeneration/GenerationForm/GenerationForm2.tsx
  src/components/ImageGeneration/GenerationForm/GenerationFormProvider.tsx
  src/components/ImageGeneration/GenerationForm/TextToImageWhatIfProvider.tsx
  src/components/ImageGeneration/GenerationForm/VideoGenerationForm.tsx
  src/components/ImageGeneration/QueueItem.tsx
  src/components/ImageGeneration/QueueSnackbar.tsx
  src/pages/moderator/test.tsx
  src/server/common/constants.ts
  src/server/controllers/orchestrator.controller.ts
  src/server/orchestrator/generation/generation.schema.ts
  src/server/orchestrator/infrastructure/base.schema.ts
  src/server/routers/orchestrator.router.ts
  src/server/services/orchestrator/orchestrator.service.ts
  src/shared/constants/generation.constants.ts
  tailwind.config.js
Labels: deploy-stage

#1616 Update GenerationForm2.tsx
  src/components/ImageGeneration/GenerationForm/GenerationForm2.tsx
Labels: enhancement

#1593 [CU-8689pngu9] Adds tour for better UX
  package-lock.json
  package.json
  src/components/AppLayout/AppHeader/CreateMenu.tsx
  src/components/Buzz/BuzzTransactionButton.tsx
  src/components/DescriptionTable/DescriptionTable.tsx
  src/components/Image/AsPosts/ImagesAsPostsCard.tsx
  src/components/Image/AsPosts/ImagesAsPostsInfinite.tsx
  src/components/Image/Infinite/ImagesCard.tsx
  src/components/ImageGeneration/GeneratedImage.tsx
  src/components/ImageGeneration/GeneratedImageActions.tsx
  src/components/ImageGeneration/GenerationForm/GenerationForm2.tsx
  src/components/ImageGeneration/GenerationProvider.tsx
  src/components/ImageGeneration/GenerationSidebar.tsx
  src/components/ImageGeneration/GenerationTabs.tsx
  src/components/ImageGeneration/Queue.tsx
  src/components/LoginRedirect/LoginRedirect.tsx
  src/components/Model/ModelCarousel/ModelCarousel.tsx
  src/components/Model/ModelVersions/ModelVersionDetails.tsx
  src/components/Orchestrator/components/GenerateButton.tsx
  src/components/Post/DeletePostButton.tsx
  src/components/Post/Detail/PostDetail.tsx
  src/components/Post/EditV2/EditPostReviews.tsx
  src/components/Post/EditV2/EditPostTags.tsx
  src/components/Post/EditV2/PostEdit.tsx
  src/components/Post/EditV2/PostEditForm.tsx
  src/components/Post/EditV2/PostEditSidebar.tsx
  src/components/ResourceReview/EditResourceReview.tsx
  src/components/Tour/TourPopover.tsx
  src/pages/_app.tsx
  src/pages/models/[id]/[[...slug]].tsx
  src/pages/posts/create.tsx
  src/providers/TourProvider.tsx
  src/server/controllers/user.controller.ts
  src/server/schema/user.schema.ts
  src/server/services/feature-flags.service.ts
  src/store/ClientHistoryStore.tsx
  src/store/generation.store.ts
  src/types/tour.ts
  src/utils/html-helpers.ts
  src/utils/login-helpers.ts
  src/utils/tours/content-gen.tour.tsx
  src/utils/tours/index.ts
  src/utils/tours/model-page.tour.tsx
  src/utils/tours/post-image-gen.tour.tsx
Labels: deploy-stage

#1633 Update index.tsx
  src/pages/creators-program/index.tsx
Labels: enhancement

#1629 Feature/creator program v2
  next.config.mjs
  package-lock.json
  package.json
  prisma/migrations/20250219230130_post_metric_index_age_group/migration.sql
  prisma/migrations/20250221023627_creators_program_v2/migration.sql
  prisma/migrations/20250221044718_add_tipalti_withdrawal_method/migration.sql
  prisma/migrations/20250227204740_make_created_at_updated_at_nullable/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/components/Account/UserPaymentConfigurationCard.tsx
  src/components/AppLayout/AppFooter.tsx
  src/components/Buzz/CreatorProgramV2/CreatorProgram.util.ts
  src/components/Buzz/CreatorProgramV2/CreatorProgramV2.modals.tsx
  src/components/Buzz/CreatorProgramV2/CreatorProgramV2.tsx
  src/components/Buzz/Rewards/DailyCreatorCompReward.tsx
  src/components/Buzz/Rewards/EarlyAccessRewards.tsx
  src/components/Dialog/Common/AlertDialog.tsx
  src/components/Signals/SignalsProvider.tsx
  src/components/Stripe/memberships.util.ts
  src/components/ToSModal/TosModal.tsx
  src/env/schema.ts
  src/pages/_app.tsx
  src/pages/api/mod/flip-phases.ts
  src/pages/api/mod/reset-bank.ts
  src/pages/api/page-view.ts
  src/pages/api/webhooks/paddle.ts
  src/pages/api/webhooks/run-jobs/[[...run]].ts
  src/pages/api/webhooks/tipalti.ts
  src/pages/creator-program/index.tsx
  src/pages/creators-program/index.tsx
  src/pages/user/buzz-dashboard.tsx
  src/pages/user/pool-estimate.tsx
  src/server/common/enums.ts
  src/server/db/db-helpers.ts
  src/server/http/tipalti/tipalti.schema.ts
  src/server/jobs/creators-program-jobs.ts
  src/server/notifications/cosmetic-shop.notifications.ts
  src/server/notifications/creators-program.notifications.ts
  src/server/redis/client.ts
  src/server/routers/creator-program.router.ts
  src/server/routers/index.ts
  src/server/schema/buzz.schema.ts
  src/server/schema/creator-program.schema.ts
  src/server/schema/user.schema.ts
  src/server/services/buzz.service.ts
  src/server/services/creator-program.service.ts
  src/server/services/user-payment-configuration.service.ts
  src/server/utils/creator-program.utils.ts
  src/shared/constants/creator-program.constants.ts
  src/shared/utils/prisma/enums.ts
  src/shared/utils/prisma/models.ts
  src/static-content/creator-program-v2-tos.md
  src/styles/globals.css
  src/types/router.ts
  src/utils/signal-client.ts
  src/utils/signals/types.ts
  src/utils/signals/useSignalsWorker.ts
  src/utils/signals/worker.ts
Labels: deploy-stage
